IMAGE_EXTENSIONS = [ "*.bmp", "*.gif", "*.jpg", "*.jpeg", "*.png", "*.pbm", "*.pgm", "*.ppm", "*.webp", "*.xbm", "*.xpm",]
LANGUAGE = [ " Japanese", " Korean", " Chinese SIM", " Chinese TRA  ", " English",]
ORIENTATION = [ " Vertical", " Horizontal",]
FONT_STYLE = [ " Helvetica", " Poppins", " Arial", " Verdana", " Times New Roman",]
FONT_SIZE = [ " 12", " 14", " 16", " 20", " 24", " 32", " 40", " 56", " 72",]
IMAGE_SCALING = [ " Fit to Width", " Fit to Height", " Fit to Screen",]
MODIFIER = [ " Ctrl", " Shift", " Alt", " Ctrl+Alt", " Shift+Alt", " Shift+Ctrl", " Shift+Alt+Ctrl", " No Modifier",]
STYLES_PATH = "./assets/"
NAV_ROOT = "./assets/images/"
TBAR_ICONS = "./assets/images/icons/"
TBAR_ICONS_LIGHT = "./assets/images/icons/"
LANG_PATH = "./assets/languages/"
STYLES_DEFAULT = "./assets/styles.qss"
LOGO = "./assets/images/icons/logo.ico"
HOME_IMAGE = "./assets/images/home.png"
ABOUT_IMAGE = "./assets/images/about.png"
TBAR_ICON_DEFAULT = "./assets/images/icons/default_icon.png"
RBN_HEIGHT = 2.4
TBAR_ISIZE_REL = 0.1
TBAR_ISIZE_MARGIN = 1.3
NAV_VIEW_RATIO = [ 3, 11,]
VIEW_IMAGE_MODE = 0
SPLIT_VIEW_MODE = false

[SELECTED_INDEX]
language = 0
orientation = 0
fontStyle = 0
fontSize = 2
imageScaling = 0
modifier = 2

[PICKER_INDEX]
language = 49
orientation = 50
fontStyle = 51
fontSize = 52
imageScaling = 53
modifier = 54

[SHORTCUT]
captureExternal = "Alt+Q"
captureExternalKey = "Q"
captureExternalTip = "This will minimize the app and perform OCR on the current screen. Alternatively, you may use the shortcut: "

[NAV_FUNCS]
pathChanged = "viewImageFromFDialog"
navClicked = "viewImageFromExplorer"

[TRANSLATE.DEEPL]
enabled = false
auth_key = ""
lang_ori = "JA"
lang_tar = "EN-US"

[TRANSLATE.GOOGLE]
enabled = true
auth_key = ""
lang_ori = "ja"
lang_tar = "en"

[TRANSLATE.YANDEX]
enabled = false
auth_key = ""
lang_ori = "JA"
lang_tar = "EN-US"

[MODE_FUNCS.zoomIn]
helpTitle = "Zoom in"
helpMsg = "Hint: Double click the image to reset zoom."
path = "zoomIn.png"
toggle = false
align = "AlignRight"
iconH = 0.45
iconW = 0.45

[MODE_FUNCS.zoomOut]
helpTitle = "Zoom out"
helpMsg = "Hint: Double click the image to reset zoom."
path = "zoomOut.png"
toggle = false
align = "AlignRight"
iconH = 0.45
iconW = 0.45

[MODE_FUNCS.loadImageAtIndex]
helpTitle = ""
helpMsg = "Jump to page"
path = "loadImageAtIndex.png"
toggle = false
align = "AlignRight"
iconH = 0.45
iconW = 1.3

[MODE_FUNCS.loadPrevImage]
helpTitle = ""
helpMsg = "Show previous image"
path = "loadPrevImage.png"
toggle = false
align = "AlignRight"
iconH = 0.45
iconW = 0.6

[MODE_FUNCS.loadNextImage]
helpTitle = ""
helpMsg = "Show next image"
path = "loadNextImage.png"
toggle = false
align = "AlignRight"
iconH = 0.45
iconW = 0.6

[TBAR_FUNCS.FILE.openDir]
helpTitle = "Open manga directory"
helpMsg = "Open a directory containing images."
path = "openDir.png"
toggle = false
align = "AlignLeft"
iconH = 1.0
iconW = 1.0

[TBAR_FUNCS.FILE.openManga]
helpTitle = "Open manga file"
helpMsg = "Supports the following formats: cbr, cbz, pdf."
path = "openManga.png"
toggle = false
align = "AlignLeft"
iconH = 1.0
iconW = 1.0

[TBAR_FUNCS.FILE.captureExternalHelper]
helpTitle = "External capture"
helpMsg = "This will minimize the app and perform OCR on the current screen. Alternatively, you may use the shortcut Alt+Q."
path = "captureExternalHelper.png"
toggle = false
align = "AlignLeft"
iconH = 1.0
iconW = 1.0

[TBAR_FUNCS.VIEW.toggleStylesheet]
helpTitle = "Change theme"
helpMsg = "Switch between light and dark mode."
path = "toggleStylesheet.png"
toggle = false
align = "AlignLeft"
iconH = 1.0
iconW = 1.0

[TBAR_FUNCS.VIEW.modifyFontSettings]
helpTitle = "Modify preview text"
helpMsg = "Change font style and font size of preview text."
path = "modifyFontSettings.png"
toggle = false
align = "AlignLeft"
iconH = 1.0
iconW = 1.0

[TBAR_FUNCS.VIEW.toggleSplitView]
helpTitle = "Turn on split view"
helpMsg = "View two images at once."
path = "toggleSplitView.png"
toggle = true
align = "AlignLeft"
iconH = 1.0
iconW = 1.0

[TBAR_FUNCS.VIEW.scaleImage]
helpTitle = "Adjust image scaling"
helpMsg = "Fit an image according to the available options: fit to width, fit to height, fit to screen"
path = "scaleImage.png"
toggle = false
align = "AlignLeft"
iconH = 1.0
iconW = 1.0

[TBAR_FUNCS.CONTROLS.toggleMouseMode]
helpTitle = "Change mouse behavior"
helpMsg = "This will disable text detection. Turn this on only if do not want to hold CTRL key to zoom and pan on an image."
path = "toggleMouseMode.png"
toggle = true
align = "AlignLeft"
iconH = 1.0
iconW = 1.0

[TBAR_FUNCS.CONTROLS.modifyHotkeys]
helpTitle = "Remap hotkeys"
helpMsg = "Change shortcut for external captures."
path = "modifyHotkeys.png"
toggle = false
align = "AlignLeft"
iconH = 1.0
iconW = 1.0

[TBAR_FUNCS.MISC.loadModel]
helpTitle = "Switch detection model"
helpMsg = "Switch between MangaOCR and Tesseract models."
path = "loadModel.png"
toggle = true
align = "AlignLeft"
iconH = 1.0
iconW = 1.0

[TBAR_FUNCS.MISC.modifyTesseract]
helpTitle = "Tesseract settings"
helpMsg = "Set the language and orientation for the Tesseract model."
path = "modifyTesseract.png"
toggle = false
align = "AlignLeft"
iconH = 1.0
iconW = 1.0

[TBAR_FUNCS.MISC.toggleLogging]
helpTitle = "Enable text logging"
helpMsg = "Save detected text to a text file located in the current project directory."
path = "toggleLogging.png"
toggle = true
align = "AlignLeft"
iconH = 1.0
iconW = 1.0
